//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowCamera {
    using Gadgeteer;
    using GTM = Gadgeteer.Modules;
    
    
    public partial class Program : Gadgeteer.Program {
        
        private Gadgeteer.Modules.GHIElectronics.Button button;
        
        private Gadgeteer.Modules.Seeed.OledDisplay oledDisplay;
        
        private Gadgeteer.Modules.GHIElectronics.Camera camera;
        
        private Gadgeteer.Modules.GHIElectronics.MulticolorLed multicolorLed;
        
        private Gadgeteer.Modules.GHIElectronics.WiFi_RS21 wifi;
        
        private Gadgeteer.Modules.GHIElectronics.UsbClientSP usbClientSP;
        
        public static void Main() {
            // Important to initialize the Mainboard first
            Program.Mainboard = new GHIElectronics.Gadgeteer.FEZSpider();
            Program p = new Program();
            p.InitializeModules();
            p.ProgramStarted();
            // Starts Dispatcher
            p.Run();
        }
        
        private void InitializeModules() {
            this.usbClientSP = new GTM.GHIElectronics.UsbClientSP(1);
            this.camera = new GTM.GHIElectronics.Camera(3);
            this.oledDisplay = new GTM.Seeed.OledDisplay(6);
            this.wifi = new GTM.GHIElectronics.WiFi_RS21(9);
            this.multicolorLed = new GTM.GHIElectronics.MulticolorLed(12);
            this.button = new GTM.GHIElectronics.Button(14);
        }
    }
}
